services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_ADDR=:${SERVER_PORT}
      - CORS_ORIGIN=localhost
